"""
Generate all 16 assets for a given CFA L1 Learning Module.
Uses the Anthropic Claude API to generate module-specific content in French.
Uses fpdf2 for PDF generation.
Usage: python generate_all_assets.py ETH LM01 "Ethics and Trust in the Investment Profession"
"""
import sys
import os
import json
import time
from pathlib import Path
from dotenv import load_dotenv

# Allow importing from app/
sys.path.insert(0, str(Path(__file__).parent))
os.environ["WINGMAN_NO_DB"] = "1"

# Load .env so ANTHROPIC_API_KEY is available
load_dotenv(Path(__file__).parent / ".env")

from app.routers.content import _markdown_to_pdf, GENERATED_ROOT
from asset_naming import asset_filename, find_asset_path

import anthropic

# ── Claude API helper ───────────────────────────────────────

MODEL = "claude-sonnet-4-20250514"
MAX_TOKENS = 4096


def _call_claude(prompt: str) -> str:
    """Call the Anthropic API and return the text response."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY is not set. "
            "Export it before running: export ANTHROPIC_API_KEY=sk-ant-..."
        )
    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text


def _clean_dot(raw: str) -> str:
    """Strip Markdown fences from a DOT response."""
    s = raw.strip()
    if s.startswith("```"):
        nl = s.index("\n")
        s = s[nl + 1:]
    if s.endswith("```"):
        s = s[:-3].rstrip()
    return s


def _render_dot_to_svg(dot_src: str, out_path: Path) -> bool:
    """Render DOT source to SVG via the `dot` binary. Returns True on success."""
    import shutil, subprocess
    if shutil.which("dot") is None:
        print("(graphviz `dot` not installed, SVG skipped)", end=" ")
        return False
    try:
        result = subprocess.run(
            ["dot", "-Tsvg", "-o", str(out_path)],
            input=dot_src.encode("utf-8"),
            capture_output=True,
            timeout=30,
        )
        if result.returncode != 0:
            print(f"(dot failed: {result.stderr.decode(errors='replace')[:120]})", end=" ")
            return False
        return True
    except Exception as exc:
        print(f"(dot error: {exc})", end=" ")
        return False


def _safe_generate(prompt: str, asset_label: str) -> str:
    """Call Claude with error handling; return placeholder on failure."""
    try:
        return _call_claude(prompt)
    except Exception as exc:
        print(f"\n    [API ERROR] {asset_label}: {exc}")
        return (
            f"# {asset_label}\n\n"
            f"**Error during automatic generation.**\n\n"
            f"The content could not be generated by the Claude API.\n"
            f"Error: {exc}\n\n"
            f"Please rerun the generation or write the content manually."
        )


# ── System context shared by all prompts ────────────────────

def _system_ctx(topic: str, lm_code: str, lm_title: str) -> str:
    return (
        f"Tu es un expert en preparation a l'examen CFA Niveau I. "
        f"Le module concerne est : sujet={topic}, code={lm_code}, titre=\"{lm_title}\". "
        f"Tout le contenu DOIT etre redige en FRANCAIS. "
        f"Utilise le vocabulaire financier francais standard (ex: 'rendement', 'obligation', 'action', 'flux de tresorerie', etc.). "
        f"Sois precis, pedagogique et oriente examen CFA Level I."
    )


# ── 16 Asset prompt builders ───────────────────────────────
# Each returns the full prompt string to send to Claude.

def prompt_summary_notes(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une FICHE DE REVISION complete en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure attendue :
- # Fiche de revision — {title}
- ## Vue d'ensemble du module (2-3 phrases)
- ## Concepts cles (avec sous-sections pour chaque concept majeur du module, definitions, formules si applicable)
- ## Points importants pour l'examen (ce que le candidat doit absolument retenir)
- ## Resume en 5 points

Sois exhaustif sur le contenu reel de ce module CFA Niveau I. Utilise le **gras** pour les termes importants."""


def prompt_synthesis(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une SYNTHESE structuree en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Synthese — {title}
- ## Introduction (contexte du module dans le cursus CFA)
- ## Themes principaux (3-6 themes avec explication detaillee)
- ## Liens entre les concepts
- ## Application pratique
- ## Conclusion

Couvre le contenu reel de ce module specifique."""


def prompt_los_sheet(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une FICHE DES LOS (Learning Outcome Statements) en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

FORMAT OBLIGATOIRE — pour CHAQUE LOS du module, utilise exactement cette structure :

---

### LOS [numero]
**[VERBE D'ACTION en majuscules]** — [intitule complet du LOS tel que defini par CFA Institute]

#### Reponse
[Paragraphe de reponse complet et precis qui repond directement au LOS. 3-5 phrases. C'est la reponse qu'un candidat doit savoir reciter.]

#### Points cles
- [Point cle 1 — detail specifique, formule ou distinction importante]
- [Point cle 2]
- [Point cle 3]
- [etc. — 4 a 8 points cles par LOS]

#### ⚠ Piege examen
[Description du piege classique lie a ce LOS specifique. Qu'est-ce que les candidats confondent ou oublient souvent ? 1-3 phrases.]

---

REGLES :
1. Couvre TOUS les LOS officiels du module (pas de LOS invente).
2. Le verbe d'action doit correspondre a la taxonomie CFA : DECRIRE, CALCULER, EXPLIQUER, COMPARER, DISTINGUER, EVALUER, INTERPRETER, etc.
3. La section "Reponse" doit etre une reponse directe et complete — pas une description vague.
4. La section "Piege examen" est OBLIGATOIRE pour chaque LOS. Si tu n'as pas de piege specifique, indique la confusion la plus courante.
5. Ecris en francais.
6. Base-toi sur les vrais LOS de ce module CFA Niveau I."""


def prompt_exam_traps(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une fiche PIEGES D'EXAMEN en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Pieges d'examen — {title}
- ## Pieges classiques (liste de 8-12 erreurs frequentes specifiques a ce module)
  - Pour chaque piege : description, pourquoi c'est trompeur, comment l'eviter
- ## Confusions courantes (paires de concepts souvent melanges)
- ## Conseils pour le jour de l'examen

Sois specifique au contenu reel de ce module."""


def prompt_concept_on_concept(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une fiche CONCEPT SUR CONCEPT en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Cette fiche superpose les concepts les uns sur les autres pour montrer comment ils s'interconnectent.

Structure :
- # Concept sur concept — {title}
- ## Carte des concepts (liste hierarchique des concepts du module)
- ## Interactions entre les concepts (comment un concept affecte un autre)
- ## Chaine logique (enchainement du raisonnement du module, etape par etape)
- ## Schema mental recommande

Utilise des fleches (→) et des listes imbriquees pour montrer les relations."""


def prompt_decision_tree(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere un ARBRE DE DECISION en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Arbre de decision — {title}
- ## Arbre principal
  Utilise un format texte avec indentation pour representer l'arbre :
  - Question/Condition → Oui/Non → Resultat ou question suivante
- ## Guide d'utilisation
- ## Cas pratiques (2-3 exemples appliquant l'arbre)

L'arbre doit couvrir les decisions/classifications cles que le candidat doit maitriser dans ce module."""


def prompt_essential_sheet(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une FICHE ESSENTIELLE (aide-memoire) en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Fiche essentielle — {title}
- ## Definitions cles (liste concise des termes importants avec definition en 1 ligne)
- ## Formules essentielles (si applicable, avec notation et explication)
- ## Regles a retenir
- ## Moyens mnemotechniques et astuces
- ## Resume ultra-compact (tout le module en 10 lignes max)

Format dense, optimise pour revision de derniere minute."""


def prompt_formula_sheet(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere un FORMULAIRE complet en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Formulaire — {title}
- ## Formules principales (chaque formule avec : nom, equation, variables definies, quand l'utiliser)
- ## Formules secondaires
- ## Relations entre les formules
- ## Exemples numeriques (1 exemple par formule principale)

Si le module ne contient pas de formules mathematiques, liste les regles, criteres ou cadres quantitatifs du module.
Utilise la notation mathematique compatible Markdown."""


def prompt_reading_summary(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere un RESUME DE LECTURE en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Resume de lecture — {title}
- ## Section par section (suit la structure de la lecture CFA)
  - Pour chaque section : resume en 3-5 phrases, points cles
- ## Vocabulaire essentiel
- ## Ce qu'il faut absolument retenir
- ## Questions de comprehension (5 questions pour verifier la comprehension)

Couvre l'integralite du contenu du module."""


def prompt_tds_sheet(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une FICHE DE TRAVAUX DIRIGES en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Travaux diriges — {title}
- ## Exercices de base (5-6 exercices avec enonces et solutions detaillees)
- ## Exercices avances (3-4 exercices plus complexes)
- ## Solutions detaillees (etape par etape)

Les exercices doivent etre representatifs du type de questions CFA Niveau I pour ce module."""


def prompt_blank_recall(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une fiche RAPPEL A BLANC en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

C'est un exercice ou le candidat doit ecrire de memoire ce qu'il sait. La fiche fournit les amorces.

Structure :
- # Rappel a blanc — {title}
- ## Consignes : sans regarder vos notes, completez les sections suivantes
- ## Concepts cles du module (laisser des lignes vides / "____" apres chaque amorce)
- ## Formules a retrouver (nom de la formule → espace vide)
- ## Definitions (terme → espace vide pour la definition)
- ## Schema a reproduire (description d'un schema/processus a redessiner)

Inclure 15-20 elements a retrouver, specifiques a ce module."""


def prompt_flashcards(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere un jeu de FLASHCARDS au format JSON pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Format EXACT attendu (JSON valide, pas de Markdown) :
{{
  "title": "Flashcards — {title}",
  "module": "{topic}-{lm}",
  "cards": [
    {{"front": "Question en francais", "back": "Reponse en francais"}},
    ...
  ]
}}

Genere 20-25 flashcards couvrant :
- Definitions des concepts cles
- Formules (si applicable)
- Distinctions entre concepts similaires
- Points frequemment testes a l'examen

IMPORTANT : retourne UNIQUEMENT le JSON, sans blocs de code Markdown, sans aucun commentaire avant ou apres."""


def prompt_mock_pack(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere un PACK DE QUESTIONS MOCK en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Pack de questions mock — {title}
- ## Consignes (simuler les conditions d'examen, 1.5 min par question)
- ## Questions (15 questions a choix multiples, chacune avec 3 choix A/B/C)
  Format par question :
  **Q1.** Enonce de la question
  - A) Option A
  - B) Option B
  - C) Option C
- ## Corrige detaille
  Pour chaque question : reponse correcte, explication, reference au concept

Les questions doivent etre au niveau de difficulte CFA Niveau I, specifiques a ce module."""


def prompt_audio_script(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere un SCRIPT AUDIO en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Ce script sera lu a voix haute (TTS) pour revision audio.

Structure :
- # Script audio — {title}
- ## Introduction (presenter le module en 2-3 phrases)
- ## Partie 1, 2, 3... (decoupage logique du contenu)
  - Expliquer chaque concept de maniere conversationnelle et claire
  - Utiliser des transitions : "Passons maintenant a...", "Un point important...", "Retenez que..."
- ## Recapitulatif final

Style : conversationnel mais precis, phrases courtes, pas de tableaux ni de formatage complexe.
Duree cible : 8-12 minutes de lecture a voix haute."""


def prompt_knowledge_audit(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere un AUDIT DE CONNAISSANCES en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Audit de connaissances — {title}
- ## Auto-evaluation (tableau avec les competences cles et une echelle 1-5)
- ## Test rapide (10 questions vrai/faux avec reponses)
- ## Questions ouvertes (5 questions necessitant une reponse redigee)
- ## Diagnostic : ou en etes-vous ? (guide d'interpretation)
- ## Plan d'action (quoi reviser en fonction du score)

L'audit doit etre specifique aux competences testees dans ce module CFA Niveau I."""


def prompt_learning_map(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une CARTE VISUELLE D'APPRENTISSAGE au format Graphviz DOT pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Cette carte sert a COMPRENDRE visuellement comment les concepts du module s'articulent (style carte conceptuelle de Novak). Ce n'est pas une hierarchie de LOS : chaque arete DOIT etre etiquetee avec un verbe qui explicite la relation entre deux concepts ("determine", "mesure", "affecte", "depend de", "se decompose en", etc.).

REGLES DE STYLE OBLIGATOIRES :
- Code de couleurs par role pedagogique :
  - VERT (#86efac) = prerequis / concepts fondamentaux a maitriser en premier
  - BLEU (#60a5fa, fontcolor=white, shape=doublecircle) = concept pivot du module (1 ou 2 max)
  - JAUNE (#fde047) = concepts derives / consequences
  - ROSE (#fbcfe8) = applications concretes / examen / monde reel
  - NOTE JAUNE PALE (#fef3c7, shape=note) = "insight cle" ou piege classique (2-3 notes)
- Aretes rouges (#dc2626) pour les liens a fort potentiel d'examen
- Aretes dashed/dotted pour differencier prerequis / liens transversaux
- rankdir=TB, splines=curved, nodesep=0.5, ranksep=0.7
- node [shape=ellipse, style=filled, fontname="Arial", fontsize=11]
- Les labels de noeuds et d'aretes DOIVENT etre en francais

STRUCTURE ATTENDUE :
digraph learning_map {{
    rankdir=TB;
    node [shape=ellipse, style=filled, fontname="Arial", fontsize=11];
    edge [fontname="Arial", fontsize=9, fontcolor="#475569"];
    graph [splines=curved, nodesep=0.5, ranksep=0.7];

    // Concepts fondamentaux (vert)
    ...

    // Concept pivot (bleu, doublecircle)
    ...

    // Concepts derives (jaune)
    ...

    // Applications (rose)
    ...

    // Relations ETIQUETEES
    NodeA -> NodeB [label="determine"];
    ...

    // Insight cle
    Insight1 [label="💡 INSIGHT\\n...", shape=note, fillcolor="#fef3c7"];
    ...
}}

CONTRAINTES :
1. 10 a 18 noeuds au total (pas plus, sinon illisible).
2. TOUTES les aretes principales doivent avoir un label (sauf celles vers les notes).
3. Au moins 2 notes "insight" (pieges, moyens mnemotechniques, relations inattendues).
4. Le contenu doit etre reellement specifique a ce module CFA Niveau I.

IMPORTANT : retourne UNIQUEMENT le code DOT valide (commencant par `digraph`). Pas de bloc Markdown, pas de commentaire avant ou apres."""


def prompt_weakness_pool(topic, lm, title):
    ctx = _system_ctx(topic, lm, title)
    return f"""{ctx}

Genere une BANQUE DE FAIBLESSES en Markdown pour le module CFA Niveau I : "{title}" ({topic}-{lm}).

Structure :
- # Banque de faiblesses — {title}
- ## Faiblesses courantes (10-15 lacunes typiques des candidats sur ce module)
  Pour chaque faiblesse :
  - Description de la lacune
  - Pourquoi c'est problematique pour l'examen
  - Exercice correctif (1 question ciblee)
  - Ressource / conseil pour combler la lacune
- ## Auto-diagnostic (checklist pour identifier ses propres faiblesses)
- ## Plan de remediation

Cible les vraies difficultes rencontrees par les candidats sur ce module specifique."""


# ── Generator registry ──────────────────────────────────────
# key → (display_title, prompt_builder, output_format)

GENERATORS = {
    "01_summary_notes":     ("Fiche de revision",           prompt_summary_notes,      "pdf"),
    "02_synthesis":         ("Synthese",                    prompt_synthesis,           "pdf"),
    "03_los_sheet":         ("Fiche des LOS",               prompt_los_sheet,           "pdf"),
    "04_exam_traps":        ("Pieges d'examen",             prompt_exam_traps,          "pdf"),
    "05_concept_on_concept":("Concept sur concept",         prompt_concept_on_concept,  "pdf"),
    "06_decision_tree":     ("Arbre de decision",           prompt_decision_tree,       "pdf"),
    "07_essential_sheet":   ("Fiche essentielle",           prompt_essential_sheet,     "pdf"),
    "08_formula_sheet":     ("Formulaire",                  prompt_formula_sheet,       "pdf"),
    "09_reading_summary":   ("Resume de lecture",           prompt_reading_summary,     "pdf"),
    "10_tds_sheet":         ("Fiche TDS",                   prompt_tds_sheet,           "pdf"),
    "11_blank_recall":      ("Rappel a blanc",              prompt_blank_recall,        "pdf"),
    "12_flashcards":        ("Flashcards",                  prompt_flashcards,          "json"),
    "13_mock_pack":         ("Pack de questions mock",      prompt_mock_pack,           "pdf"),
    "14_audio_script":      ("Script audio",                prompt_audio_script,        "md"),
    "15_knowledge_audit":   ("Audit de connaissances",      prompt_knowledge_audit,     "pdf"),
    "16_weakness_pool":     ("Banque de faiblesses",        prompt_weakness_pool,       "pdf"),
    "17_learning_map":      ("Carte visuelle d'apprentissage", prompt_learning_map,     "dot"),
}


def _existing_asset_file(module_dir: Path, key: str, fmt: str, topic: str = "", lm_code: str = "") -> Path | None:
    """Return the existing on-disk file for `key`, or None. Used by skip-existing.

    Tries the new naming convention `<TOPIC>-<LM>-<key>.<ext>` first, then falls
    back to the legacy bare `<key>.<ext>` so older modules keep working.
    """
    if fmt == "json":
        exts = [".json"]
    elif fmt == "md":
        exts = [".md"]
    elif fmt == "dot":
        exts = [".svg", ".dot"]
    else:
        exts = [".pdf"]
    if topic and lm_code:
        return find_asset_path(module_dir, topic, lm_code, key, exts)
    # Legacy fallback (callers that don't pass topic/lm_code)
    for ext in exts:
        p = module_dir / f"{key}{ext}"
        if p.exists():
            return p
    return None


def generate_all(topic: str, lm_code: str, lm_title: str, skip_existing: bool = False):
    """Generate all 16 assets for a given LM using the Claude API.

    When `skip_existing` is True, assets whose output file is already present
    on disk are left untouched — the run only fills the gaps. Stdout still
    prints a "Generating ... OK (skipped)" line so progress trackers stay
    aligned with the canonical 17-step sequence.
    """
    module_dir = GENERATED_ROOT / topic / lm_code
    module_dir.mkdir(parents=True, exist_ok=True)

    assets = []
    start = time.time()

    for key, (title, prompt_builder, fmt) in GENERATORS.items():
        if skip_existing:
            existing = _existing_asset_file(module_dir, key, fmt, topic, lm_code)
            if existing is not None:
                size_kb = round(existing.stat().st_size / 1024, 1)
                assets.append({"title": title, "filename": existing.name, "size_kb": size_kb, "status": "success"})
                print(f"  Generating {key} ({title})... OK (skipped, {size_kb} KB)", flush=True)
                continue

        print(f"  Generating {key} ({title})...", end=" ", flush=True)

        prompt = prompt_builder(topic, lm_code, lm_title)
        content = _safe_generate(prompt, title)

        if fmt == "json":
            # Clean up potential markdown code fences from the response
            cleaned = content.strip()
            if cleaned.startswith("```"):
                # Remove opening fence (```json or ```)
                first_newline = cleaned.index("\n")
                cleaned = cleaned[first_newline + 1:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3].rstrip()
            # Validate JSON
            try:
                json.loads(cleaned)
                content = cleaned
            except json.JSONDecodeError:
                print("(Invalid JSON, using raw content)", end=" ")

            filename = asset_filename(topic, lm_code, key, ".json")
            filepath = module_dir / filename
            filepath.write_text(content, encoding="utf-8")
        elif fmt == "md":
            filename = asset_filename(topic, lm_code, key, ".md")
            filepath = module_dir / filename
            filepath.write_text(content, encoding="utf-8")
        elif fmt == "dot":
            dot_src = _clean_dot(content)
            dot_filename = asset_filename(topic, lm_code, key, ".dot")
            dot_path = module_dir / dot_filename
            dot_path.write_text(dot_src, encoding="utf-8")
            svg_filename = asset_filename(topic, lm_code, key, ".svg")
            svg_path = module_dir / svg_filename
            if _render_dot_to_svg(dot_src, svg_path) and svg_path.exists():
                filename = svg_filename
                filepath = svg_path
            else:
                filename = dot_filename
                filepath = dot_path
        else:
            filename = asset_filename(topic, lm_code, key, ".pdf")
            filepath = module_dir / filename
            _markdown_to_pdf(content, str(filepath), title, f"{topic}-{lm_code}")

        size_kb = round(filepath.stat().st_size / 1024, 1)
        assets.append({"title": title, "filename": filename, "size_kb": size_kb, "status": "success"})
        print(f"OK ({size_kb} KB)")

    elapsed = round(time.time() - start, 1)

    # Write manifest
    manifest = {
        "module": {"topic": topic, "code": f"{topic}-{lm_code}", "title": lm_title},
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "total_time_sec": elapsed,
        "assets": assets,
    }
    manifest_path = module_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"\n  Done! {len(assets)} assets in {elapsed}s -> {module_dir}")
    return manifest


def generate_one(topic: str, lm_code: str, lm_title: str, asset_key: str):
    """Generate a single asset for a given LM."""
    if asset_key not in GENERATORS:
        print(f"Unknown asset key: {asset_key}")
        print(f"Available keys: {', '.join(GENERATORS.keys())}")
        sys.exit(1)

    module_dir = GENERATED_ROOT / topic / lm_code
    module_dir.mkdir(parents=True, exist_ok=True)

    title, prompt_builder, fmt = GENERATORS[asset_key]
    print(f"  Generating {asset_key} ({title})...", end=" ", flush=True)

    prompt = prompt_builder(topic, lm_code, lm_title)
    content = _safe_generate(prompt, title)

    if fmt == "json":
        cleaned = content.strip()
        if cleaned.startswith("```"):
            first_newline = cleaned.index("\n")
            cleaned = cleaned[first_newline + 1:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3].rstrip()
        try:
            json.loads(cleaned)
            content = cleaned
        except json.JSONDecodeError:
            print("(Invalid JSON, using raw content)", end=" ")
        filename = asset_filename(topic, lm_code, asset_key, ".json")
        filepath = module_dir / filename
        filepath.write_text(content, encoding="utf-8")
    elif fmt == "md":
        filename = asset_filename(topic, lm_code, asset_key, ".md")
        filepath = module_dir / filename
        filepath.write_text(content, encoding="utf-8")
    elif fmt == "dot":
        dot_src = _clean_dot(content)
        dot_filename = asset_filename(topic, lm_code, asset_key, ".dot")
        dot_path = module_dir / dot_filename
        dot_path.write_text(dot_src, encoding="utf-8")
        svg_filename = asset_filename(topic, lm_code, asset_key, ".svg")
        svg_path = module_dir / svg_filename
        if _render_dot_to_svg(dot_src, svg_path) and svg_path.exists():
            filename = svg_filename
            filepath = svg_path
        else:
            filename = dot_filename
            filepath = dot_path
    else:
        filename = asset_filename(topic, lm_code, asset_key, ".pdf")
        filepath = module_dir / filename
        _markdown_to_pdf(content, str(filepath), title, f"{topic}-{lm_code}")

    size_kb = round(filepath.stat().st_size / 1024, 1)
    print(f"OK ({size_kb} KB)")

    # Update manifest
    manifest_path = module_dir / "manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    else:
        manifest = {
            "module": {"topic": topic, "code": f"{topic}-{lm_code}", "title": lm_title},
            "generated_at": "",
            "total_time_sec": 0,
            "assets": [],
        }
    # Remove old entry for same asset if exists
    manifest["assets"] = [a for a in manifest["assets"] if a["filename"] != filename]
    manifest["assets"].append({"title": title, "filename": filename, "size_kb": size_kb, "status": "success"})
    manifest["generated_at"] = time.strftime("%Y-%m-%d %H:%M:%S")
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    return {"title": title, "filename": filename, "size_kb": size_kb}


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage:")
        print("  All:  python generate_all_assets.py TOPIC LM_CODE [TITLE]")
        print("  One:  python generate_all_assets.py TOPIC LM_CODE TITLE --asset ASSET_KEY")
        sys.exit(1)

    t = sys.argv[1].upper()
    lm = sys.argv[2].upper()
    title = sys.argv[3] if len(sys.argv) > 3 and not sys.argv[3].startswith("--") else f"{t}-{lm}"

    # Check for --asset flag
    if "--asset" in sys.argv:
        idx = sys.argv.index("--asset")
        if idx + 1 < len(sys.argv):
            asset_key = sys.argv[idx + 1]
            print(f"Generating single asset {asset_key} for {t}/{lm} — {title}")
            generate_one(t, lm, title, asset_key)
        else:
            print("Error: --asset requires a value")
            sys.exit(1)
    else:
        skip = "--skip-existing" in sys.argv
        print(f"Generating all assets for {t}/{lm} — {title}{' (skip-existing)' if skip else ''}")
        generate_all(t, lm, title, skip_existing=skip)
