'use client'

import { useRef, useState } from 'react'

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'

interface AudioPlayerProps {
  assetId: number
  title: string
  onClose: () => void
}

export default function AudioPlayer({ assetId, title, onClose }: AudioPlayerProps) {
  const audioRef = useRef<HTMLAudioElement>(null)
  const [playing, setPlaying] = useState(false)

  const skip = (seconds: number) => {
    if (audioRef.current) {
      audioRef.current.currentTime += seconds
    }
  }

  return (
    <div className="card">
      <div className="flex items-center justify-between mb-3">
        <h2 className="card-header mb-0">Audio Player</h2>
        <button onClick={onClose} className="text-slate-400 hover:text-white text-sm">Close</button>
      </div>

      <p className="text-sm text-slate-300 mb-4">{title}</p>

      <audio
        ref={audioRef}
        src={`${API_URL}/api/content/asset/${assetId}`}
        onPlay={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
        className="hidden"
      />

      <div className="flex items-center justify-center gap-4">
        <button onClick={() => skip(-15)} className="btn-ghost text-xs">-15s</button>
        <button
          onClick={() => {
            if (audioRef.current) {
              playing ? audioRef.current.pause() : audioRef.current.play()
            }
          }}
          className="w-12 h-12 rounded-full bg-accent-blue flex items-center justify-center text-white text-lg hover:bg-blue-600 transition"
        >
          {playing ? '\u23F8' : '\u25B6'}
        </button>
        <button onClick={() => skip(15)} className="btn-ghost text-xs">+15s</button>
      </div>

      <p className="text-xs text-slate-500 text-center mt-3">
        Note: In production, audio files will be generated by Edge TTS
      </p>
    </div>
  )
}
