#!/usr/bin/env python3
"""Build a Level 1 'Active Discovery' fiche PDF for one Learning Module.

Spec:
  - 1 LM = 1 PDF.
  - Number of cards = number of QBank questions with difficulty ∈ {1, 2}
    (very_easy + easy) for the LM. No cap.
  - Order: by `standard_citation` then question id.
  - Each card =
      Header: question stem + 3 choices (verbatim from QBank, in EN) + correct letter
      ── Then 5 FR teaching blocks generated by Claude:
      ① Rappel de cours
      ② Formule (si nécessaire — null otherwise)
      ③ Raisonnement
      ④ Résolution détaillée
      ⑤ Détails calculatrice BA II Plus (null if non-calculation)
  - Cognitive autonomy: every prerequisite explained inline.
  - Bilingual policy: question + choices in EN (verbatim from QBank), all 5
    teaching blocks in FR. No translation work.
  - Rendered with WeasyPrint, can span multiple pages per card.

CLI:
    python build_level1_fiche.py <topic> <lm_code> [--limit N] [--force]

The DB-side LM code is `<TOPIC>-<NN>` (e.g. QM-01) — we accept either form
on the command line.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from html import escape
from pathlib import Path
from typing import Optional

SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = SCRIPT_DIR.parent
GENERATED_ROOT = BACKEND_DIR / "generated_content"
sys.path.insert(0, str(BACKEND_DIR))

CSS_BASE = SCRIPT_DIR / "wingman_light.css"
CSS_LEVEL1 = SCRIPT_DIR / "level1_card.css"
MODEL = "claude-sonnet-4-6"
MAX_TOKENS_PER_CARD = 2500


SYSTEM_PROMPT = """\
Tu produis une fiche Wingman "Active Discovery" Niveau 1 pour le CFA Level 1.
Une seule carte = une seule question QBank. Ton rôle : encoder le concept par
un geste cognitif minimal, avec autonomie cognitive totale — l'étudiant ne
doit avoir besoin de rien d'autre que cette carte.

Tu reçois la question (en anglais, verbatim QBank) et tu produis 5 blocs
pédagogiques **en français**. Tu ne traduis PAS la question : elle reste en
anglais dans la fiche.

Règles :
- Niveau 1 → simple, direct, pas de finesse inutile.
- Si la question mobilise un concept secondaire (ex. covariance utilisée pour
  bêta), inclus un rappel intégré de ce concept dans le bloc Rappel.
- Notation math : utilise les caractères Unicode (σ, ρ, Σ, π, β, α, ²) et
  des indices/exposants Markdown (`σ_p`, `w_1²`, `ρ_{i,j}`, `2^n`). Pas de
  LaTeX, pas de MathML.
- Markdown léger autorisé : **gras**, *italique*, listes `-`.

Tu réponds UNIQUEMENT par un objet JSON, sans aucun texte avant ou après,
avec ce schéma exact :

{
  "rappel_cours": "string (3-6 lignes, en français)",
  "formule": "string ou null si pas de formule applicable",
  "raisonnement": "string (3-6 lignes, en français)",
  "resolution": "string (étape par étape, avec les nombres, finit sur la réponse)",
  "calculatrice": "string ou null si question non calculatoire"
}

Règle de cohérence formule ↔ calculatrice :
- Si tu donnes une `formule`, alors tu DOIS donner les `calculatrice` (séquence
  BA II Plus correspondante, même si la séquence est triviale type "saisir
  les valeurs et additionner"). Une formule sans calculatrice est interdit.
- Si la question est purement conceptuelle (aucun calcul, aucune formule
  applicable), alors `formule` ET `calculatrice` sont tous deux null.

Format obligatoire du bloc `calculatrice` (BA II Plus) :
1. **Toujours commencer par un reset** du menu utilisé (jamais "saisir
   directement"). Le reset adapté au menu :
     - TVM    → `[2nd][CLR TVM]`
     - CF     → `[CF] [2nd][CLR Work]`
     - STAT   → `[2nd][DATA] [2nd][CLR Work]`
     - BOND   → `[2nd][BOND] [2nd][CLR Work]`
     - ICONV  → `[2nd][ICONV] [2nd][CLR Work]`
     - AMORT  → `[2nd][AMORT] [2nd][CLR Work]`
     - DEPR / DATE / PROB / BRKEVN → idem `[2nd][<menu>] [2nd][CLR Work]`
     - Pas de menu (calcul direct sur le ruban) → `[2nd][RESET][ENTER]`
2. **Nommer explicitement le menu** sur la première ligne après le reset
   (ex. "Menu TVM", "Menu CF (Cash Flow)", "Menu STAT en mode LIN").
3. **Notation des touches** : entre crochets et en majuscules — `[N]`,
   `[I/Y]`, `[PV]`, `[PMT]`, `[FV]`, `[CPT]`, `[ENTER]`, `[↓]`, `[NPV]`,
   `[IRR]`. Une touche par crochet, séquences enchaînées avec espaces :
   `12 [N]  8 [I/Y]  −1000 [PV]  0 [PMT]  [CPT][FV]`.
4. **Une étape = une ligne** sous forme de liste à puces `-`. Annoter la
   sortie attendue (`→ FV ≈ 2,158.92`).
5. Si le calcul peut se faire dans plusieurs menus, choisir **le plus
   pédagogique** pour le concept (NPV/IRR → CF, jamais TVM ; conversion
   nominal↔effective → ICONV, jamais formule manuelle ; bond price → BOND
   ou TVM selon que le coupon est uniforme).
6. Pour les calculs purement arithmétiques (somme, produit, division
   simple), pas besoin de menu : reset général + opérations directes au
   ruban suffisent. Mais le reset reste obligatoire.
"""


USER_TEMPLATE = """\
Module : CFA L1 {topic_name} — {lm_title}
LO : {los_anchor}
Citation : {standard_citation}

Question (EN, verbatim QBank) :
{stem}

A. {choice_a}
B. {choice_b}
C. {choice_c}

Bonne réponse : {correct_answer}
Explication QBank :
{explanation}

Produis l'objet JSON pour la fiche Active Discovery Niveau 1.
"""


# ── DB access (uses backend's existing DSN) ───────────────────────────────

def fetch_questions(topic: str, lm_num: str) -> list[dict]:
    """Fetch very_easy + easy questions for the LM. Uses asyncpg under the
    hood (the only Postgres driver shipped in the backend container).

    `lm_num` is the 2-digit suffix (e.g. '01'). Rows are ordered by
    standard_citation then id."""
    import asyncio
    import asyncpg
    # asyncpg wants a plain `postgresql://` URL.
    db_url = os.environ["DATABASE_URL"].replace("postgresql+asyncpg://", "postgresql://")

    async def _run():
        conn = await asyncpg.connect(db_url)
        try:
            rows = await conn.fetch(
                """
                SELECT q.id, q.difficulty, q.los_anchor, q.stem,
                       q.choice_a, q.choice_b, q.choice_c, q.correct_answer,
                       q.explanation, q.standard_citation, lm.title AS lm_title
                FROM questions q
                JOIN learning_modules lm ON q.module_id = lm.id
                WHERE lm.code = $1
                  AND q.disabled_at IS NULL
                  AND q.difficulty IN (1, 2)
                ORDER BY q.standard_citation NULLS LAST, q.id
                """,
                f"{topic.upper()}-{lm_num}",
            )
            return [dict(r) for r in rows]
        finally:
            await conn.close()

    return asyncio.run(_run())


# ── Claude call ──────────────────────────────────────────────────────────

def call_claude(client, topic_name: str, lm_title: str, question: dict) -> dict:
    user = USER_TEMPLATE.format(
        topic_name=topic_name,
        lm_title=lm_title,
        los_anchor=question.get("los_anchor") or "",
        standard_citation=question.get("standard_citation") or "",
        stem=question["stem"],
        choice_a=question["choice_a"],
        choice_b=question["choice_b"],
        choice_c=question["choice_c"],
        correct_answer=question["correct_answer"],
        explanation=question.get("explanation") or "(aucune)",
    )
    resp = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS_PER_CARD,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user}],
    )
    raw = resp.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1].rsplit("```", 1)[0].strip()
    lb, rb = raw.find("{"), raw.rfind("}")
    if lb >= 0 and rb > lb:
        raw = raw[lb:rb + 1]
    blocks = json.loads(raw)
    # Defensive defaults.
    for k in ("rappel_cours", "formule", "raisonnement", "resolution", "calculatrice"):
        blocks.setdefault(k, None)
    # Enforce the formule ↔ calculatrice coherence rule even if Claude slips.
    # When a formule is present but Claude returned calculatrice = null (usually
    # a trivial-sum case), inject a minimal reset-only sequence so the bloc is
    # always present and the visual structure stays uniform.
    if blocks.get("formule") and not blocks.get("calculatrice"):
        blocks["calculatrice"] = (
            "Reset général : `[2nd][RESET][ENTER]`.\n"
            "Calcul direct au ruban (pas de menu spécialisé requis) : "
            "saisir les valeurs et appliquer la formule ci-dessus.\n"
            "→ Lire le résultat affiché."
        )
    usage = {
        "input_tokens": resp.usage.input_tokens,
        "output_tokens": resp.usage.output_tokens,
    }
    return {"blocks": blocks, "usage": usage}


# ── Math notation + light markdown for FR blocks ─────────────────────────

_MATH_RULES = [
    (re.compile(r"([A-Za-zρσμνπθβαγδλΣΩ])(²|³)?_\{([^{}]+)\}"),
     lambda m: f"{m.group(1)}{m.group(2) or ''}<sub>{m.group(3)}</sub>"),
    # Match accented chars too — Claude writes things like `r_réel`, `RP_défaut`,
    # `π_anticipée`. The trailing accented letter must stay inside the <sub>.
    (re.compile(r"([A-Za-zρσμνπθβαγδλΣΩ])(²|³)?_([A-Za-zÀ-ÿ0-9*]+)"),
     lambda m: f"{m.group(1)}{m.group(2) or ''}<sub>{m.group(3)}</sub>"),
    # Caret superscript: `2^n`, `(1+r)^t`, `e^x`. We don't require a word
    # boundary before `^` so `)^t` works too.
    (re.compile(r"\^([A-Za-zÀ-ÿ0-9]+)"),
     lambda m: f"<sup>{m.group(1)}</sup>"),
]

_BOLD = re.compile(r"\*\*(.+?)\*\*")
_ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")
_CODE = re.compile(r"`([^`]+)`")


def render_inline(text: str) -> str:
    parts: list[str] = []
    last = 0
    for m in _CODE.finditer(text):
        if m.start() > last:
            parts.append(_render_prose(text[last:m.start()]))
        parts.append(f'<span class="math">{escape(m.group(1))}</span>')
        last = m.end()
    if last < len(text):
        parts.append(_render_prose(text[last:]))
    return "".join(parts)


def _render_prose(text: str) -> str:
    text = escape(text, quote=False)
    for pat, repl in _MATH_RULES:
        text = pat.sub(repl, text)
    text = _BOLD.sub(r"<strong>\1</strong>", text)
    text = _ITALIC.sub(r"<em>\1</em>", text)
    return text


def render_block(text: str) -> str:
    """Render a multi-line block: detect bullet lists, paragraphs."""
    if not text:
        return ""
    lines = text.split("\n")
    out: list[str] = []
    para_buf: list[str] = []
    list_buf: list[str] = []

    def flush_para():
        if para_buf:
            out.append(f"<p>{render_inline(' '.join(s.strip() for s in para_buf))}</p>")
            para_buf.clear()

    def flush_list():
        if list_buf:
            out.append("<ul>" + "".join(f"<li>{render_inline(s)}</li>" for s in list_buf) + "</ul>")
            list_buf.clear()

    for line in lines:
        s = line.rstrip()
        if not s.strip():
            flush_para(); flush_list()
            continue
        m = re.match(r"^\s*-\s+(.*)$", s)
        if m:
            flush_para()
            list_buf.append(m.group(1))
            continue
        flush_list()
        para_buf.append(s)
    flush_para(); flush_list()
    return "\n".join(out)


def render_formula_block(text: str) -> str:
    """A formula block uses the same `.eq` style as the structured builder.
    Multi-line formulas are rendered as separate `.eq` rows."""
    out: list[str] = []
    for raw in text.split("\n"):
        s = raw.strip()
        if not s:
            continue
        # Strip leading bullet if any.
        s = re.sub(r"^-\s+", "", s)
        # Escape ONCE up-front, then apply substitutions. Escaping inside the
        # loop would re-encode the <sub>/<sup> tags emitted by an earlier rule.
        s = escape(s, quote=False)
        for pat, repl in _MATH_RULES:
            s = pat.sub(repl, s)
        s = _BOLD.sub(r"<strong>\1</strong>", s)
        out.append(f'<div class="eq">{s}</div>')
    return "".join(out)


# ── Card rendering ────────────────────────────────────────────────────────

CARD_TEMPLATE = """\
<article class="card-l1" id="card-{idx}">
  <header class="card-head">
    <span class="card-num">Carte {num}/{total}</span>
    <span class="card-meta">{los}</span>
  </header>
  {pre_question_blocks}
  <section class="block block-question">
    <div class="block-title"><span class="block-num">③</span>Question (CFA L1 — {citation})</div>
    <div class="block-body">
      <div class="q-stem">{stem}</div>
      <ol class="q-choices" type="A">
        <li>{ca}</li>
        <li>{cb}</li>
        <li>{cc}</li>
      </ol>
      <div class="q-correct">Bonne réponse : <strong>{correct}</strong></div>
    </div>
  </section>
  {post_question_blocks}
</article>
"""


BLOCK_TEMPLATE = """\
<section class="block block-{kind}">
  <div class="block-title"><span class="block-num">{num}</span>{label}</div>
  <div class="block-body">{body}</div>
</section>
"""


# Order matches the user's spec:
#   ① Rappel de cours · ② Formule (optionnel) · ③ Question (from QBank, hard-coded
#   in CARD_TEMPLATE) · ④ Raisonnement · ⑤ Résolution · ⑥ Détails calculatrice.
BLOCKS_BEFORE_QUESTION = [
    ("rappel_cours",  "①", "Rappel de cours", "rappel"),
    ("formule",       "②", "Formule",         "formule"),
]
BLOCKS_AFTER_QUESTION = [
    ("raisonnement",  "④", "Raisonnement",                    "raisonnement"),
    ("resolution",    "⑤", "Résolution détaillée",            "resolution"),
    ("calculatrice",  "⑥", "Détails calculatrice BA II Plus", "calc"),
]


def _render_blocks(defs, blocks: dict) -> str:
    out: list[str] = []
    for key, num, label, kind in defs:
        body_text = blocks.get(key)
        if not body_text:
            continue  # Skip null blocks (formule absent, calc N/A).
        body = render_formula_block(body_text) if kind == "formule" else render_block(body_text)
        out.append(BLOCK_TEMPLATE.format(num=num, label=label, kind=kind, body=body))
    return "\n".join(out)


def render_card(idx: int, total: int, q: dict, blocks: dict) -> str:
    return CARD_TEMPLATE.format(
        idx=idx,
        num=idx,
        total=total,
        los=escape(q.get("los_anchor") or ""),
        citation=escape(q.get("standard_citation") or ""),
        stem=escape(q["stem"]),
        ca=escape(q["choice_a"]),
        cb=escape(q["choice_b"]),
        cc=escape(q["choice_c"]),
        correct=escape(q["correct_answer"]),
        pre_question_blocks=_render_blocks(BLOCKS_BEFORE_QUESTION, blocks),
        post_question_blocks=_render_blocks(BLOCKS_AFTER_QUESTION, blocks),
    )


def render_cover(topic_name: str, topic_fr: str, module_num: str, lm_title: str, n_cards: int) -> str:
    return (
        f'<div class="title-page">'
        f'<div class="topic-bar">{escape(topic_name).upper()}</div>'
        f'<div class="module-num">Learning Module {module_num} · Active Discovery</div>'
        f'<h1 class="module-title">{escape(lm_title)}</h1>'
        f'<div class="accent"></div>'
        f'<div class="module-title-fr">Niveau 1 — Encodage Actif</div>'
        f'<div class="subtitle">{n_cards} cartes générées à partir de la QBank '
        f'(very_easy + easy). Question en EN, raisonnement et calcul en FR. '
        f'Tout est contenu dans la carte — autonomie cognitive intégrale.</div>'
        f'<div class="footer-meta"><span class="brand">Wingman</span> · CFA Level 1 · Active Discovery</div>'
        f'</div>'
        f'<span class="topic-name">{escape(topic_fr)}</span>'
    )


def build_html(topic_name: str, topic_fr: str, module_num: str, lm_title: str, cards: list[str]) -> str:
    body = "".join(cards)
    return (
        f'<!DOCTYPE html><html lang="fr"><head>'
        f'<meta charset="utf-8"><title>{escape(lm_title)} — Active Discovery</title>'
        f'</head><body>'
        f'{render_cover(topic_name, topic_fr, module_num, lm_title, len(cards))}'
        f'{body}'
        f'</body></html>'
    )


def write_pdf(html: str, output: Path):
    from weasyprint import CSS, HTML
    HTML(string=html, base_url=str(SCRIPT_DIR)).write_pdf(
        str(output),
        stylesheets=[CSS(filename=str(CSS_BASE)), CSS(filename=str(CSS_LEVEL1))],
    )


# ── CLI ──────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("topic", help="Topic code, e.g. QM")
    parser.add_argument("lm_code", help="LM code, e.g. LM01 or 01")
    parser.add_argument("--limit", type=int, default=None, help="Process only the first N questions (for sampling)")
    parser.add_argument("--output", default=None, help="Output PDF path (default: <generated>/<TOPIC>/<LM>/level1_active_discovery.pdf)")
    args = parser.parse_args()

    topic = args.topic.upper()
    lm = args.lm_code.upper().replace("LM", "").lstrip("0") or "0"
    lm_num = lm.zfill(2)
    lm_dir = GENERATED_ROOT / topic / f"LM{lm_num}"
    if not lm_dir.exists():
        print(f"[ERREUR] LM dir introuvable : {lm_dir}", file=sys.stderr)
        return 1

    output = Path(args.output) if args.output else lm_dir / "level1_active_discovery.pdf"

    # Topic display names — same source as the audio-script builder.
    from wingman_course_builder.topics import topic_name_en, topic_name_fr_short
    topic_name = topic_name_en(topic)
    topic_fr = topic_name_fr_short(topic)

    print(f"Querying QBank for {topic}-{lm_num} (very_easy + easy)…")
    questions = fetch_questions(topic, lm_num)
    if not questions:
        print(f"[ERREUR] Aucune question very_easy/easy trouvée pour {topic}-{lm_num}", file=sys.stderr)
        return 1
    if args.limit:
        questions = questions[:args.limit]
    n = len(questions)
    lm_title = questions[0].get("lm_title") or f"{topic}-{lm_num}"
    print(f"  → {n} cartes à produire pour « {lm_title} »")

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("[ERREUR] ANTHROPIC_API_KEY absent", file=sys.stderr)
        return 1
    import anthropic
    client = anthropic.Anthropic(api_key=api_key)

    cards_html: list[str] = []
    total_in = total_out = 0
    for i, q in enumerate(questions, start=1):
        print(f"  [{i}/{n}] qid={q['id']} (d={q['difficulty']}) {q['los_anchor'][:60] if q.get('los_anchor') else ''}…", end=" ", flush=True)
        try:
            res = call_claude(client, topic_name, lm_title, q)
        except json.JSONDecodeError as e:
            print(f"FAIL: JSON parse — {e}")
            continue
        except Exception as e:
            print(f"FAIL: {type(e).__name__}: {e}")
            continue
        blocks = res["blocks"]
        u = res["usage"]
        total_in += u["input_tokens"]; total_out += u["output_tokens"]
        cards_html.append(render_card(i, n, q, blocks))
        skipped = [k for k in ("formule", "calculatrice") if not blocks.get(k)]
        print(f"OK ({u['input_tokens']}+{u['output_tokens']} tok{', skip ' + '/'.join(skipped) if skipped else ''})")

    if not cards_html:
        print("[ERREUR] Aucune carte produite", file=sys.stderr)
        return 1

    html = build_html(topic_name, topic_fr, lm_num, lm_title, cards_html)
    print(f"Rendering PDF ({len(cards_html)} cartes)…")
    write_pdf(html, output)

    # Cost estimate (Sonnet 4.6: $3/Mtok input, $15/Mtok output).
    cost = total_in / 1e6 * 3 + total_out / 1e6 * 15
    print(f"PDF: {output}")
    print(f"Tokens: in={total_in:,} out={total_out:,} — cost ≈ ${cost:.3f}")
    try:
        from pypdf import PdfReader
        r = PdfReader(str(output))
        print(f"QC: {len(r.pages)} pages")
    except Exception:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
