"""Build db/seed_missing_los_v2.sql from /tmp/los_compare/B.json."""
import json
from pathlib import Path

B = json.loads(Path("/tmp/los_compare/B.json").read_text())
TARGETS = [r["module_code"] for r in B["results"]]

def esc(s: str) -> str:
    return s.replace("'", "''")

lines: list[str] = []
lines.append("-- =============================================================")
lines.append("-- Wingman — Seed LOS v2 (Claude Sonnet 4.6, 5-7 LOS per module)")
lines.append("-- Replaces sparse / mismatched LOS for 27 modules.")
lines.append("-- Generated by scripts/build_seed_v2_sql.py from /tmp/los_compare/B.json")
lines.append("-- =============================================================")
lines.append("")
lines.append("BEGIN;")
lines.append("")
lines.append("-- 1. Remove existing LOS for the 27 target modules")
codes_csv = "','".join(TARGETS)
lines.append(f"""DELETE FROM learning_outcomes
WHERE module_id IN (
    SELECT id FROM learning_modules WHERE code IN ('{codes_csv}')
);""")
lines.append("")
lines.append("-- 2. Insert v2 LOS")

for r in B["results"]:
    if "los" not in r:
        lines.append(f"-- SKIP {r['module_code']}: no LOS in B output")
        continue
    mod = r["module_code"]
    title = r["module_title"].replace("--", "-")
    lines.append(f"-- ----- {mod}: {title} -----")
    lines.append("INSERT INTO learning_outcomes (module_id, code, description, bloom_level, sort_order) VALUES")
    rows: list[str] = []
    for i, lo in enumerate(r["los"], 1):
        bloom = max(1, min(6, int(lo.get("bloom_level", 2))))
        code = f"{mod}-LO{i:02d}"
        desc = esc(lo["description"])
        rows.append(f"    ((SELECT id FROM learning_modules WHERE code='{mod}'), '{code}', '{desc}', {bloom}, {i})")
    lines.append(",\n".join(rows) + ";")
    lines.append("")

lines.append("COMMIT;")
lines.append("")

import os
out = Path(os.environ.get("OUTPUT", "db/seed_missing_los_v2.sql"))
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out}, {out.stat().st_size} bytes, {sum(len(r.get('los',[])) for r in B['results'])} LOS")
